spring:
    application:
        name: order
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: 3DSmart
        url: jdbc:mysql://127.0.0.1:3306/springcloud_sell?characterEncoding=utf-8&useSSL=false
    jpa:
        show-sql: true
            
         
server:
    port: 8082

env:
     dev3

girl:
    name: lili
    age: 10
